name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
        
    - name: Build and push PHP Docker image
      run: |
        docker build -t php:8-fpm-alpine -f path/to/php/dockerfile .
        docker push php:8-fpm-alpine
        
    - name: Build and push MySQL Docker image
      run: |
        docker pull mysql:latest
        docker tag mysql:latest mysql:latest
        docker push mysql:latest
        
    - name: Build and push Nginx Docker image
      run: |
        docker pull nginx:latest
        docker tag nginx:latest nginx:latest
        docker push nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Install Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
        
    - name: Pull Docker images from Docker Hub
      run: |
        docker pull php:8-fpm-alpine
        docker pull mysql:latest
        docker pull nginx:latest

    - name: Deploy with Docker Compose
      run: docker-compose up -d