FROM php:8.1-fpm-alpine

RUN apk update && apk upgrade
RUN apk add git unzip zip

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && php -r "unlink('composer-setup.php');"

COPY .env /var/www/html/.env
COPY src/composer.json /var/www/html/composer.json

RUN docker-php-ext-install pdo pdo_mysql
RUN chown -R www-data:www-data /var/www/html
WORKDIR /var/www/html
RUN composer install