FROM php:8.1-fpm-alpine

RUN apk update && apk upgrade
RUN apk add git unzip zip wget

RUN wget https://getcomposer.org/composer-stable.phar -O /usr/local/bin/composer && chmod +x /usr/local/bin/composer

COPY .env /var/www/html/.env
COPY src/composer.json /var/www/html/composer.json

RUN docker-php-ext-install pdo pdo_mysql
RUN chown -R www-data:www-data /var/www/html
WORKDIR /var/www/html
# Copie le script de démarrage personnalisé
COPY start.sh /usr/local/bin/start.sh

# Donne les permissions d'exécution au script de démarrage
RUN chmod +x /usr/local/bin/start.sh

# Démarre le conteneur en utilisant le script de démarrage personnalisé
CMD ["/usr/local/bin/start.sh"]